import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import AuthContext from './context/AuthContext';
import ToasterContext from './context/ToasterContext';
import PrelineContext from './context/PrelineContext';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <AuthContext>
          <PrelineContext>
            <ToasterContext />
            {children}
          </PrelineContext>
        </AuthContext>
      </body>
    </html>
  );
}
